apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenlun-kivra
  annotations:
    github.com/project-slug: jenlun-kivra/jenlun-kivra
    backstage.io/techdocs-ref: ./docs/
spec:
  type: other
  lifecycle: unknown
  owner: jenlun-kivra
